# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0418\u043c\u044f')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='\u042d\u043b. \u043f\u043e\u0447\u0442\u0430')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
            ],
            options={
                'db_table': 'client',
                'verbose_name': '\u041a\u043b\u0438\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u043b\u0438\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('price', models.FloatField(verbose_name='\u0426\u0435\u043d\u0430 \u0442\u043e\u0432\u0430\u0440\u0430 $')),
                ('final_price', models.FloatField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0435\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430 $')),
                ('status', models.CharField(max_length=255, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('order_number', models.CharField(max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('link_to_product', models.CharField(max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043f\u0440\u043e\u0434\u0443\u043a\u0442')),
                ('site_which_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0430\u0439\u0442 \u0441 \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0432\u0437\u044f\u0442')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043d\u043e')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e')),
                ('extra_field', models.TextField(verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e')),
                ('done', models.BooleanField(default=False, verbose_name='\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u0437\u0430\u043a\u0430\u0437')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_models.Client', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442')),
                ('manager', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u041c\u0435\u043d\u0435\u0434\u0436\u0435\u0440')),
            ],
            options={
                'db_table': 'orders',
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('color', models.CharField(max_length=100, verbose_name='\u0426\u0432\u0435\u0442 \u0442\u0435\u0433\u0430')),
            ],
            options={
                'db_table': 'tag',
                'verbose_name': '\u0422\u0435\u0433',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='tags',
            field=models.ManyToManyField(to='crm_models.Tag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
