# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_models', '0002_auto_20161221_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_models.Client', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442'),
        ),
    ]
