# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_models', '0004_auto_20161226_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('label-info', '\u0413\u043e\u043b\u0443\u0431\u043e\u0439'), ('label-danger', '\u041a\u0440\u0430\u0441\u043d\u044b\u0439'), ('label-success', '\u0437\u0435\u043b\u0451\u043d\u044b\u0439'), ('label-warning', '\u0416\u0451\u043b\u0442\u044b\u0439'), ('label-primary', '\u0421\u0438\u043d\u0438\u0439')], max_length=100, verbose_name='\u0426\u0432\u0435\u0442 \u0442\u0435\u0433\u0430'),
        ),
    ]
